version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"
    ENV: "dev"
    TF_DIR: "awscicd/jenkins-server"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - wget -q https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -q terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "ENV=$ENV | TF_DIR=$TF_DIR"
      - cd $TF_DIR
      - terraform init -backend-config="backend/${ENV}.hcl" -reconfigure -input=false
      - pwd
      - ls -lrt
      - find . -name "tfplan*"
      - ls -lrt /codebuild/output/src*/src/s3/01
      - find /codebuild/output/src*/src/s3/01 -name "tfplan*"

  build:
    commands:
      - echo "Terraform Apply ENV=${ENV}"
      - terraform apply -auto-approve $(find /codebuild/output -name tfplan-${ENV})

  post_build:
    commands:
      - echo "Apply complete for ENV=${ENV}"
      - terraform output
