version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"
    TF_WORKING_DIR: "awscicd/jenkins-server"
    # ENV will be passed from CodeBuild/CodePipeline environment variable
    # Values: dev | nonprod | prod

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Terraform $TF_VERSION"
      - wget -q https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -q terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "== Initializing Terraform for ENV=$ENV =="
      - cd $TF_WORKING_DIR
      - |
        terraform init -backend-config="backend/${ENV}.hcl" -reconfigure

  build:
    commands:
      - echo "== Running Terraform Validate =="
      - terraform validate
      - echo "== Running Terraform Plan for ENV=$ENV =="
      - |
        terraform plan -var-file="env/jenkins-${ENV}.tfvars" -out=tfplan-${ENV} -input=false
      - echo "Plan complete"

  post_build:
    commands:
      - echo "== Plan phase finished for ENV=$ENV =="

artifacts:
  base-directory: $TF_WORKING_DIR
  files:
    - tfplan-${ENV}
    - "**/*"
  discard-paths: no
