version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.11

    commands:
      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform_1.8.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Changing Directory"
      - pwd
      - cd awscicd/jenkins-server
      - echo "Terraform Init"
      - pwd
      - terraform init -reconfigure -backend-config=awscicd/jenkins-server/backend/dev.hcl

  build:
    commands:
      - echo "Terraform Format Check"
      - terraform fmt -check -recursive
      - echo "Terraform Validate"
      - terraform validate
      - echo "Terraform Plan"
      - terraform plan -var-file=awscicd/jenkins-server/env/jenkins-dev.tfvars

  post_build:
    commands:
      - echo "Terraform Apply"
      - terraform apply -auto-approve -var-file=awscicd/jenkins-server/env/jenkins-dev.tfvars
