version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"
    ENV: "dev"
    TF_DIR: "awscicd/jenkins-server"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Terraform ${TF_VERSION}"
      - wget -q https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -q terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "ENV=$ENV | TF_DIR=$TF_DIR"
      - cd $TF_DIR
      - echo "Current dir $(pwd)"
      - ls -la backend/
      - terraform init -backend-config="backend/${ENV}.hcl" -reconfigure -input=false

  build:
    commands:
      - terraform validate
      - echo "Terraform Plan ENV=${ENV}"
      - terraform plan -destroy -var-file="env/jenkins-${ENV}.tfvars" -out=destroyplan-${ENV}
      - pwd
      - ls -lrt
      - find . -name "destroyplan*"

  post_build:
    commands:
      - echo "Plan complete for ENV=${ENV}"

artifacts:
  base-directory: awscicd/jenkins-server
  files:
    - destroyplan-${ENV}
    - "**/*"
  discard-paths: no
